# Generated by Django 5.0.1 on 2024-01-09 14:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='link',
            managers=[
                ('links', django.db.models.manager.Manager()),
            ],
        ),
    ]
